// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLI8wudx_QZovGQr_gUd1HtSLwA-KrVZE',
    appId: '1:107668853359:web:084102551dcc680206739a',
    messagingSenderId: '107668853359',
    projectId: 'driveme-cd63e',
    authDomain: 'driveme-cd63e.firebaseapp.com',
    databaseURL: 'https://driveme-cd63e-default-rtdb.firebaseio.com',
    storageBucket: 'driveme-cd63e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYgVOb8eKjJxU0_53_YnrExOHu8BwBlYU',
    appId: '1:107668853359:android:4365caa223e4656806739a',
    messagingSenderId: '107668853359',
    projectId: 'driveme-cd63e',
    databaseURL: 'https://driveme-cd63e-default-rtdb.firebaseio.com',
    storageBucket: 'driveme-cd63e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCml6WaAfQqCjVV9lHHLKftqPtAqIvqGDI',
    appId: '1:107668853359:ios:0d92138a7838b2fd06739a',
    messagingSenderId: '107668853359',
    projectId: 'driveme-cd63e',
    databaseURL: 'https://driveme-cd63e-default-rtdb.firebaseio.com',
    storageBucket: 'driveme-cd63e.appspot.com',
    iosClientId: '107668853359-sblvu2ddu0pq5c3g9a446qrkt1nhtoea.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberClone',
  );
}
